[tool.poetry]
name = "pheval"
version = "0.1.0"
description = ""
authors = ["Nico Matentzoglu <nicolas.matentzoglu@gmail.com>", "Vinícius de Souza <souzadevinicius@gmail.com>"]
readme = "README.md"
packages = [{include = "pheval", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9"
jaydebeapi = ">=1.2.3"
tqdm = ">=4.64.1"
pandas = ">=1.5.1"
deprecation = ">=2.1.0"
click = ">=8.1.3"
class-resolver = "^0.3.10"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
coverage = "^6.5.0"

[tool.poetry.scripts]
pheval = "pheval.cli:pheval"
pheval-utils = "pheval.cli:pheval_utils"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.2"
pymdown-extensions = "^9.9"
mkdocs-material = "^8.5.11"
mkdocstrings = "^0.19.1"
mkdocstrings-python = "^0.8.2"
mkdocs-include-dir-to-nav = "^1.2.0"
mkdocs-click = "^0.8.0"

[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
