phenotype:
  version: 2302
  hg: hg19
  url: https://data.monarchinitiative.org/exomiser/latest/


directories:
  tmp: data/tmp
  testdata: testdata
  config: configurations
  h2jar: /home/vinicius/.local/share/DBeaverData/drivers/maven/maven-central/com.h2database/h2-1.4.199.jar
  phen2gene: /home/vinicius/Documents/softwares/Phen2Gene
  exomiser: /home/data/exomiser-data/
  phenotype: /home/data/exomiser-data/2302_phenotype


#when we run the make preparation (not default) we should create symlink if they don't exists in default 


configs:
  - tool: phen2gene
    version: 1.2.3
    configuration: default
  - tool: exomiser
    version: 13.2.0
    configuration: default
    exomiser_db: semsim1
  - tool: exomiser
    version: 13.2.0
    configuration: semsim1
    description: Exomiser Deafault Configuration with a Randomised Semantic Similarity Profile
    exomiser_db: semsim1
  




runs:
  - tool: phen2gene
    configuration: default
    corpus: corpus1
    corpusvariant: 0.5
    version: 1.2.3
  - tool: exomiser
    configuration: default
    corpus: corpus1
    corpusvariant: 1
    version: 13.2.0
  - tool: exomiser
    configuration: default
    corpus: corpus2
    corpusvariant: 0.3
    version: 13.2.0

